apiVersion: v1
kind: Pod
metadata:
  name: nginx-distroless-pod
  labels:
    app: nginx-distroless
spec:
  containers:
  - name: nginx-distroless-container
    image: kyos0109/nginx-distroless
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
          #    securityContext:
          #      capabilities:
          #        add: [ "SYS_PTRACE" ]
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-distroless-service
spec:
  selector:
    app: nginx-distroless
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-distroless-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: nd.homework.otus
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-distroless-service
            port:
              number: 80
