apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : myapp1
  namespace: oyus
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: app1
  source:
    path   : "kubernetes-gitops"
    repoURL: "git@github.com:Kuber-2024-08OTUS/AlexAndAyub_repo.git"
    targetRevision: kubernetes-gitops
    helm:
      valueFiles:
      - values_dev.yaml
      parameters:
      - name: "container.image"
        value: hello-world

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

