apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
spec:
  destination:
    name: ''
    namespace: otus
    server: https://kubernetes.default.svc
  source:
    path: kubernetes-gitops/app
    repoURL: git@github.com:Kuber-2024-08OTUS/AlexAndAyub_repo.git
    targetRevision: kubernetes-gitops
  sources: []
  project: otus
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - ApplyOutOfSyncOnly=true

