apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ng
  template:
    metadata:
      labels:
        app: ng
    spec:
      containers:
      - name: ng
        image: my\ng
        ports:
        - containerPort: 80
        - containerPort: 9113
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: exporter-config
          mountPath: /etc/nginx-prometheus-exporter.conf
          subPath: exporter.conf
        resources:
          requests:
            memory: "200Mi"
            cpu: "250m"
          limits:
            memory: "400Mi"
            cpu: "500m"
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: exporter-config
        configMap:
          name: exporter-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: homework
data:
  nginx.conf: |
    events {}

    http {
        server {
            listen 80;

            location / {
                root /usr/share/nginx/html;
                index index.html index.htm;
            }

            location /stub_status {
                stub_status;
                allow 127.0.0.1;
                deny all;
            }
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: exporter-config
  namespace: homework
data:
  exporter.conf: |
    nginx:
      scrape-uri: http://localhost:80/stub_status
    web:
      listen-address: ":9113"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: homework
spec:
  selector:
    app: ng
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
    - protocol: TCP
      port: 9113
      targetPort: 9113
      name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: nginx
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
  namespaceSelector:
    matchNames:
    - homework