apiVersion: v1
kind: ConfigMap
metadata:
  name: homework-my-configmap
  namespace: homework
  labels:
    les: kubernetes-intro
data:
  nginx_conf: |
    events {}
    http {
      server {
          # define error page
          error_page 404 = /err404.html;
          error_page 500 = /err500.html;
          
          listen 8000;

          location / {
            #autoindex on;
            root /homework;
            try_files $uri $uri/index.html =404;
          }

          location /conf/file {
            alias /homework/conf/file/;
          }
      }
    }
  index_html: |
    fio: MinkovAV
    city: Ufa
    age: 41
