apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: consul
    name: in-cluster
  project: default
  source:
    path: HelmCharts/consul
    repoURL: git@192.168.0.42:minkovav/argocd.git
    targetRevision: master                            #Ветка
    helm:
      valueFiles:
        - consul-values.yaml
  project: home
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
