apiVersion: ops.otus.homework/v1alpha1
kind: Project
metadata:
  labels:
    app.kubernetes.io/name: mysql-operator
    app.kubernetes.io/managed-by: kustomize
  name: project-sample
spec:
  # TODO(user): Add fields here
