apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-sql
  labels:
    app: my-sql
  namespace: {{ .Values.nameSpace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: web-server
  template:
    metadata:
      labels:
        run: web-server
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: MYSQL_HOST
              value: {{ .Release.Name }}-mysql
            - name: MYSQL_USER
              value: {{ .Values.mysql.mysqlUser }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.mysqlPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.mysqlDatabase }}
