apiVersion: v1
kind: PersistentVolume
metadata:
  name: homework-my-pv
spec:
  storageClassName: "homework-storage"
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/homework-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: homework
              operator: In
              values:
                - "true"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homework-my-pvc
  namespace: homework
spec:
  storageClassName: "homework-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

