apiVersion: v1
kind: Service
metadata:
  name: srv-mypod
  namespace: {{ .Values.nameSpace}}
  labels:
    run: web-server
spec:
  type: {{ .Values.service.type }}
  selector:
    run: web-server
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000

