apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: otus
spec:
  destination:
    namespace: otus
    name: test-home-work
  project: default
  source:
    path: kubernetes-gitops/HelmCharts/MyChart1
    repoURL: git@github.com:Kuber-2024-08OTUS/AlexAndAyub_repo.git
    targetRevision: HEAD
