apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: otus
spec:
  destination:
    namespace: otus
    name: test-home-work
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
