apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: homework
  labels:
    les: kubernetes-intro
data:
  nginx.conf: |
    events {}
    http {
      server {
          listen 8000;
          root /homework;

          location / {
            autoindex on;
          }
      }
    }
---

apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: homework
  labels:
    name: mypod
    les: kubernetes-intro
spec:
  volumes:
    - name: shared-volume
      emptyDir: {}
    - name: nginx-config-volume
      configMap:
        name: nginx-config
  initContainers:
    - name: init-container
      image: busybox
      command:
        - /bin/sh
        - -c
        - |
          d=$(date +'%Y-%m-%d %H:%M:%S')
          echo "<html><body><h1>My pod in k3s. Created: $d  </h1></body></html>" > /init/index.html
      volumeMounts:
        - name: shared-volume
          mountPath: /init
  containers:
    - name: web-server
      image: nginx:alpine
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: shared-volume
          mountPath: /homework
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      lifecycle:
        preStop:
          exec:
            command:
              - /bin/sh
              - -c
              - |
                rm -f /homework/index.html
---

apiVersion: v1
kind: Service
metadata:
  name: srv-mypod
  namespace: homework
  labels:
    les: kubernetes-intro
spec:
  selector:
    name: mypod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-ingress
  namespace: homework
  labels:
    les: kubernetes-intro
spec:
  ingressClassName: traefik
  rules:
    - host: mypod.my.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: srv-mypod
                port:
                  number: 80
