apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: homework
  labels:
    name: mypod
spec:
  volumes:
    - name: shared-volume
      emptyDir: {}
  initContainers:
    - name: init-container
      image: busybox
      command:
        - /bin/sh
        - -c
        - |
          d=$(date +'%Y-%m-%d %H:%M:%S')
          echo "<html><body><h1>My pod in k3s. Created: $d  </h1></body></html>" > /init/index.html
      volumeMounts:
        - name: shared-volume
          mountPath: /init
  containers:
    - name: web-server
      image: nginx:alpine
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: shared-volume
          mountPath: /homework
      lifecycle:
        preStop:
          exec:
            command:
              - /bin/sh
              - -c
              - |
                rm -f /homework/index.html

